### ISSUE TITLE
Clean up Ramsey\Uuid usage

### ISSUE THREAD

**Issue by asm89** [broadway/broadway#255]
Broadway should only use https://github.com/qandidate-labs/broadway-uuid-generator.

**Comment by Lavoaster** [comment]
Would this update the version of `ramsey\uuid` to the 3.x series?

**Comment by mbadolato** [comment]
@asm89 
What's needed to do here besides remove the requirement from broadway's composer.json and update broadway-uuid-generator to use the latest ramsey\uuid (3.x)? I'm having a hell of a time installing and using Broadway when I have uuid 3.x in place. I'll happily submit a patch 😄 

I haven't looked into the codebase in while. Offhand, does broadway use the ramsey uuid package directly, thus needing changes too?

**Comment by othillo** [comment]
the DBALEventStore uses it: https://github.com/qandidate-labs/broadway/blob/master/src/Broadway/EventStore/DBALEventStore.php#L209

**Comment by mbadolato** [comment]
If that's the only place it's used then a fromString() pass-through/delegator could easily be added to https://github.com/qandidate-labs/broadway-uuid-generator/blob/master/src/Broadway/UuidGenerator/Rfc4122/Version4Generator.php. Since broadway-uuid is already required by broadway, we have access to Version4Generator throughout the package so that method could delegate and we could remove the package from here.

Any opposition to that? @qandidate-labs

**Comment by othillo** [comment]
That would violate SRP, wouldn't it?
What we need is a 2-way string uuid to binary uuid converter.
Naming suggestions anyone? :)

**Comment by mbadolato** [comment]
> That would violate SRP, wouldn't it?

Yeaaaaah I suppose it would seeing as it's named Generator

**Comment by othillo** [comment]
comments are welcome: https://github.com/qandidate-labs/broadway-uuid-generator/pull/9
