### ISSUE TITLE
Split components in separate composer packages

### ISSUE THREAD

**Issue by stof** [broadway/broadway#5]
Given that components are fully decoupled (or mostly at least, as I haven't checked every classes), it would make sense to distribute them as separate Composer packages to allow users to depend only on the part they need.
For the bundle, it would also allow to define its real dependencies instead of listing them as `suggest` in the global composer.json and having the bundle break if they are not installed (it breaks if DoctrineBundle is not there btw, and DoctrineBundle is not even listed). Optional requirements are always a pain to manage, because you cannot put any constraint about the version of the other package to be used (well, you could do some stuff with `conflicts`, but it is not easy).

there is 2 alternatives for this:
1. develop in the main repo and then provide subtree-splits for each component. This is the way Symfony does it. It requires having a hook updating the subtrees each time the main repo gets updated.
   
   | Pros | Cons |
   | --- | --- |
   | All development in one place | Complex to setup |
   | Easy to test/change coupled parts | Release cycle is coupled |
2. develop each component in their own repo, dropping the main repo (after creating subtree splits).
   
   | Pros | Cons |
   | --- | --- |
   | Easy to setup (no updating server needed) | development is split in several places |
   | Each component can be released separately when needed | harder to change coupled parts in non-BC ways |
   | Easy for contributors to contribute on the component they use |  |

Given that there is almost no coupling between components, the second alternative probably wins in this case

**Comment by asm89** [comment]
@cboden linked me the scripts the react project was using previously: https://github.com/reactphp/react/tree/17044db0ab6a9c145fb1ac40822c5c17d045dc36/scripts

**Comment by ruudk** [comment]
+1

**Comment by asm89** [comment]
If anyone has concrete ideas about how to do this, I'd be happy to look into it. As said before, we'd like to stabilize the components a bit more before doing a final split into separate repositories. We could go the subtree split way, but that can be quite cumbersome as well?

**Comment by harikt** [comment]
The recent zf3 will be splitting to repos which can accepts PR . If you are still with the subtree split, may be you should ping Fabien, Taylor, Beau or Stof for the same.

**Comment by haampie** [comment]
Some inactivity here, but there are some solid reasons I encountered to proceed. The doctrine/mongodb package is currently problematic when using PHP7, since the doctrine package relies on the old ext-mongo extension, while PHP7 is (only?) shipped with ext-mongodb. See https://github.com/doctrine/mongodb/issues/239 which runs sinds December 2015.

Of course I can simply remove the mongodb dev dependency, but it would be reassuring to run all of the project tests rather than excluding some.

It shouldn't be too much of a hassle to split specific implementations (DBal / ElasticSearch / MongoDB) from interfaces, right? Except for InMemory implementations maybe :)

**Comment by haampie** [comment]
Another reason; the filter query used in the ElasticSearch repository is deprecated in ElasticSearch 2.3+

https://www.elastic.co/guide/en/elasticsearch/reference/2.3/breaking_20_query_dsl_changes.html#_literal_filtered_literal_query_and_literal_query_literal_filter_deprecated

**Comment by othillo** [comment]
Closing this, because at the moment we have split the
* Symfony bundle: https://github.com/broadway/broadway-bundle
* Saga: https://github.com/broadway/broadway-saga
* DBAL event store: https://github.com/broadway/event-store-dbal
* Elasticsearch read models: https://github.com/broadway/read-model-elasticsearch

Some still need to be merged but then we have split at least the all the implementations.

**Comment by harikt** [comment]
no composer.json ?

**Comment by othillo** [comment]
@harikt these PR's are still open:
- [ ] https://github.com/broadway/event-store-dbal/pull/1/files
- [ ] https://github.com/broadway/read-model-elasticsearch/pull/1

**Comment by harikt** [comment]
@othillo any reason it is still waiting ?

**Comment by othillo** [comment]
it needs code review and merge, /cc @broadway/broadway ;)
